### ISSUE TITLE
CSP failure in consumeres of ember-auto-import 

### ISSUE THREAD

**Issue by sandstrom** [ef4/ember-auto-import#275]
If a consuming app doesn't allow eval (via CSP) and the addon doesn't explicitly tell ember-auto-import to forbid eval, the compiled output will contain eval statements which will cause failure in the consuming app.

What's the performance cost? May I suggest that we drop eval altogether? Or at least always drop it when running within the context of an addon (vs an app).

**Comment by ef4** [comment]
> The consuming app does not use ember-auto-import.

Even when the consuming app doesn't use ember-auto-import, the app is allowed to include configuration (including `forbidEval`) in order to control how its addons use ember-auto-import.

This got fixed in https://github.com/ef4/ember-auto-import/pull/213

**Comment by sandstrom** [comment]
@ef4 That's good! 

But it's still a problem that when, for example, one of my addons switch to ember-auto-import my app breaks + it breaks in a fairly non-obvious way.

Is there a big performance difference when not using eval?

How about dropping eval when running within the context of an addon?

**Comment by ef4** [comment]
Picking a different default when the app itself doesn't use ember-auto-import is a reasonable idea.

**Comment by sandstrom** [comment]
@ef4 Yeah, that would be great I think!

**Comment by sandstrom** [comment]
@ef4 I've made a stab at it here: https://github.com/ef4/ember-auto-import/issues/275

No idea if that's a good route to go down. Feel free to discard everything or make any changes you'd like to that PR. I've given you access to the branch, so edit at will.

Also not sure how one would check if the root package is using this addon or not! I guessed an empty options object may be an indicator, but I'm not sure about that.

**Comment by jelhan** [comment]
> Picking a different default when the app itself doesn't use ember-auto-import is a reasonable idea.

Maybe the default could also depend on the presence of ember-cli-content-security-policy? There might be cases in which the app depends on the ember-cli-content-security-policy addon but it's disabled for local development. There might be even cases in which the app uses it but includes `'unsafe-eval'` in `script-src`. But both scenarios aren't the common ones.

**Comment by adong** [comment]
Add the following config to `ember-cli-build.js` has worked for us.

```
let app = new EmberApp(defaults, {
    autoImport: {
      forbidEval: true
    },
```
